### ISSUE TITLE
Re-generating da-y-wrapper causes error in the browser

### ISSUE THREAD

**Issue by bosschaert** [adobe/da-live#200]
When re-generating `da-y-wrapper` even without any changes, the result produces the following error in the browser console when editing a DA page:

```
TypeError: Cannot read properties of undefined (reading 'state')
    at il.dispatchTransaction (index.js:107:32)
    at il.dispatch (index.js:8:46597)
    at index.js:12:8601
    at ao.mux (index.js:12:3924)
    at ao._forceRerender (index.js:12:8377)
    at Object.view (index.js:12:5740)
    at il.updatePluginViews (index.js:8:44335)
    at new il (index.js:8:41375)
    at initProse (index.js:281:17)
    at DaEditor.updated (da-editor.js:91:25)
```

Here's what I did:
1. Take a fresh clone of da-live, run `npm i`
2. Sanity check before doing anything -> `aem up` and check a page on localhost:3000 and see that it works, then kill the process.
4. run `npm run build:da-y-wrapper`
5. run `aem up` again and then go to the same page. The editor won't properly load and the exception above can be seen in the browser console.

**Comment by bosschaert** [comment]
Re-opening because the live preview was still broken.
